# docker network create -d bridge --gateway 172.22.0.1 --subnet 172.22.0.0/24 --attachable my_private_network
# mysql -h 172.22.0.10 -u root -p'password'

version: '3.1'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    networks:
      default:
        ipv4_address: 172.22.0.10
    volumes:
      - "./mysql_data:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
  phpmyadmin_web:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    volumes:
      - './config.user.inc.php:/etc/phpmyadmin/config.user.inc.php'
    environment:
      PMA_HOST: mysql_db 
      UPLOAD_LIMIT: 50000000
    networks:
      default:
        ipv4_address: 172.22.0.11

networks:
  default:
    external:
      name: my_private_network
